### ISSUE TITLE
[mobile] Logo/menu button clash

### ISSUE THREAD

**Issue by rphi** [qaisjp/compsoc-website#10]
On non-home pages, the logo overlaps the menu button a bit (Nexus 5x) Also menu button shifts on click on the home page.

![screenshot_20170721-074219](https://user-images.githubusercontent.com/8237136/28452094-ea741a92-6de8-11e7-9a7c-4e35ed222fe9.png)

**Comment by qaisjp** [comment]
perhaps we could show `compsoc-icon.png` instead of the full width logo on small devices?

**Comment by qaisjp** [comment]
this might be useful https://stackoverflow.com/questions/30745573/bootstrap-navbar-brand-logo-overlapping-on-collapse
