### ISSUE TITLE
Community page responsiveness

### ISSUE THREAD

**Issue by rphi** [qaisjp/compsoc-website#13]
(created from @qaisjp's card)

**Comment by rphi** [comment]
Partial fix in #12 .

**Comment by qaisjp** [comment]
Please use [flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) :)

**Comment by rphi** [comment]
I believe at least for the Facebook thing, the size needs to be set in the data-height attribute prior to the fb javascript sdk being called to generate the object? So something more dynamic wouldn't work as far as I can see? (the fb js sdk generates the iframe when it is run so we can't style that?)

**Comment by qaisjp** [comment]
very good point, we may have to do some naughty hacky behaviour here

**Comment by bnelo12** [comment]
I was thinking just having bootstrap stack the columns on mobile.

**Comment by qaisjp** [comment]
Oh yep sorry that works

**Comment by rphi** [comment]
Yeah just set the classes as col-md then it will stack on anything smaller
of you have them in container and row divs.

(Also if you get this you can reply by email :shock:)

On 22 Jul 2017 5:16 pm, "Ben Elo" <notifications@github.com> wrote:

I was thinking just having bootstrap stack the columns on mobile.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/qaisjp/compsoc-website/issues/13#issuecomment-317193708>,
or mute the thread

**Comment by rphi** [comment]
Still seems to be misbehaving for me on Chrome and Safari - I'll take a look

![screen shot 2017-07-23 at 17 28 41](https://user-images.githubusercontent.com/8237136/28501092-6440dad8-6fcc-11e7-8894-c16d4ceca599.png)

**Comment by bnelo12** [comment]
Interesting, it seems to be working for me on Chrome and safari. Is your branch up to date?

**Comment by rphi** [comment]
I just forked and pulled?
